find_package(doctest REQUIRED)

function(add_solver_test name)
    add_executable(${name} ${name}.cpp)
    target_link_libraries(${name} PRIVATE doctest::doctest)
    add_test(NAME ${name} COMMAND ${name} WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR})
endfunction()

add_solver_test(csv-parser-test)
add_solver_test(flipper-test)
add_solver_test(formula-test)
add_solver_test(merger-test)
add_solver_test(number-incrementor-test)
add_solver_test(number-inserter-test)
add_solver_test(operation-producer-test)
add_solver_test(operation-replacer-test)
add_solver_test(purger-test)
add_solver_test(solver-test)
add_solver_test(tree-test)
add_solver_test(kinetic-energy-test)
add_solver_test(gravity-test)