#ifndef GENERIC_SOLVER_CHANGERS_BASE_HPP
#define GENERIC_SOLVER_CHANGERS_BASE_HPP

#include "../utils/arbitrary.hpp"
#include "formula.hpp"

enum SolverState {
    BROKEN,
    PAUSED,
    READY,
    RUNNING,
    DONE
};

enum ChangerType {
    FLIPPER,
    INCREMENTOR_BY_DOUBLING,
    INCREMENTOR_BY_FRAGMENT,
    INCREMENTOR_BY_ONE,
    MERGER,
    NUMBER_INSERTER,
    OPERATION_PRODUCER,
    OPERATION_REPLACER,
    REDUCER_BY_DOUBLING,
    REDUCER_BY_FRAGMENT,
    REDUCER_BY_ONE
};

static vector<ChangerType> CHANGERS(
        {FLIPPER, INCREMENTOR_BY_DOUBLING, INCREMENTOR_BY_FRAGMENT, INCREMENTOR_BY_ONE, MERGER, NUMBER_INSERTER,
         OPERATION_PRODUCER, OPERATION_REPLACER, REDUCER_BY_DOUBLING, REDUCER_BY_FRAGMENT, REDUCER_BY_ONE});

#endif